name = "Morbit"
uuid = "88936782-c8cd-4a0f-b259-ffb12bfd2869"
authors = ["manuelbb <manuelbb@mail.uni-paderborn.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
